spring:
  datasource:
    url: jdbc:postgresql://maglev.trolley.rlwy.net:25706/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
